### ISSUE TITLE
Terminology for distinguishing the microcontrollers from the rest of the product range

### ISSUE THREAD

**Issue by michaelstoops** [raspberrypi/style-guide#21]
I'd like to write some documentation that calls out features of the Raspberry Pi 1, 2B, 3B, 4B, Zero, Zero W, and compute modules, but **doesn't** include the microcontroller range.

What are we calling the non-microcontroller devices as a group?
* "non-microcontrollers" is accurate at this time, but what about some third group that shows up?
* "full" or other indication of size seems tempting, but the Zero, A, and B variants range widely in their size, so that might not work.
* "Linux-capable" is probably relevant to most users, but is only accurate if you ignore the Linux ports to RP2040.

Do we have a preferred terminology for these device classes?

**Comment by helenlynn** [comment]
Oh look, a neglected issue; sorry. Yes, @lurch is right, we use "Raspberry Pi computers" for the non-microcontroller devices; you are, of course, free to use this or something that seems more suitable for documentation that you are writing.

**Comment by aallan** [comment]
I... didn't even know this repo existed, or would have been opinionated about this before now!

"Raspberry Pi computers" is certainly what I've been doing/calling them, or "single board computers" if I really have to, while our microcontroller range is "Raspberry Pi microcontroller boards" (or "microcontroller devices" if we're talking chips).

Colloquially I use the term "mainline" for the big boards, or in fact "big boards" sometimes when speaking. But I wouldn't really like to see it written down.

**Comment by lurch** [comment]
@aallan Is it maybe worth linking to this repo from e.g. https://github.com/raspberrypi/documentation/blob/develop/CONTRIBUTING.md ?
