### ISSUE TITLE
RPT?

### ISSUE THREAD

**Issue by lurch** [raspberrypi/style-guide#22]
Raspberry Pi Trading isn't included in the wordlist yet...
I see that https://custompc.raspberrypi.org/about (and https://magpi.raspberrypi.org/about ) uses "Raspberry Pi Trading Ltd." but https://www.raspberrypi.org/documentation/ uses "Raspberry Pi (Trading) Ltd" and https://www.raspberrypi.org/about/ uses "Raspberry Pi (Trading) Limited" ?

**Comment by andrum99** [comment]
Per Companies House, the legal name of the company is `Raspberry Pi (Trading) Limited`. Limited companies in both England & Wales, and Scotland, are permitted to abbreviate `Limited` to `Ltd.`

**Comment by andrum99** [comment]
Also, there's nothing I can find on Trading's website that has the required information about that company, per the Companies (Trading Disclosures) Regulations 2008. Note that the information need not be on every page, but must be easily accessible.

Also, per the Electronic Commerce (EC Directive) Regulations 2002 (see https://www.legislation.gov.uk/uksi/2002/2013/contents/made), Trading is required to disclose their VAT number on their website.

**Comment by andrum99** [comment]
And the 'Trademark Rules' page on Trading's website (https://www.raspberrypi.com/trademark-rules/) incorrectly states that the trademarks are owned by Trading - this is not the case - see https://trademarks.ipo.gov.uk/ipo-tmowner/page/search?id=831641&domain=1&app=0&mark=UK00918188560 - choose one of the trademarks and click the `names and addresses` tab to reveal the owner's name as `Raspberry Pi Foundation`.
