### ISSUE TITLE
Switchmode power supply

### ISSUE THREAD

**Issue by Wren6991** [raspberrypi/style-guide#26]
RP2350 has a ~switched-mode~ um ~switch-mode~ uh ~switchmode power supply~ uhhh, SMPS.

What's the canonical way of writing this?

**Comment by aallan** [comment]
I mean, I'd probably say "switched mode", but it's more properly a @helenlynn question.

**Comment by kehribar** [comment]
So, another chip with dual M3 / M33 core with 512kb ram? 

Sounds very exciting.
